fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.0.0"
    "concat":
      repo: "git@github.com:puppetlabs/puppetlabs-concat.git"
      ref: "1.1.2"
  symlinks:
    "display": "#{source_dir}"
