language: ruby
script:
  - "bundle exec puppet --version"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - '[ "$PUPPET_GEM_VERSION" == ">= 3.7.0" ] && bundle exec rake future'
rvm:
 - 1.8.7
 - 1.9.3-p484
 - 2.0.0
 - ruby-head
env:
 - PUPPET_GEM_VERSION=">= 3.7.0"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 2.7"
notifications:
  email: false
